spring:
  application:
    name: file-upload

okta:
  oauth2:
    issuer:
    client-id:
    client-secret:

  sdk:
    url:
    response_type: token
    redirect_uri: http://localhost:8080/authorization-code/callback
    response_mode: okta_post_message
    scope: internal
    client_id: